/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CJunCmsLogoutDialog: typeof import('./src/dialogs/CJunCmsLogoutDialog.vue')['default']
    CJunCmsPageLayout: typeof import('./src/layouts/CJunCmsPageLayout.vue')['default']
    ElAutoResizer: typeof import('element-plus/es')['ElAutoResizer']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPane: typeof import('element-plus/es')['ElPane']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTableV2: typeof import('element-plus/es')['ElTableV2']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IEpMenu: typeof import('~icons/ep/menu')['default']
    IEpPlus: typeof import('~icons/ep/plus')['default']
    IEpSwitchButton: typeof import('~icons/ep/switch-button')['default']
    LeftBar: typeof import('./src/components/LeftBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SysIcon: typeof import('./src/components/SysIcon.vue')['default']
    TabBar: typeof import('./src/components/TabBar.vue')['default']
    Topbar: typeof import('./src/components/Topbar.vue')['default']
    TopBar: typeof import('./src/components/TopBar.vue')['default']
    UserBar: typeof import('./src/components/UserBar.vue')['default']
  }
}
