// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCjDemandProject = "cj_demand_project"

// CjDemandProject mapped from table <cj_demand_project>
type CjDemandProject struct {
	DemandID  uint32    `gorm:"column:demand_id;type:int unsigned;primaryKey" json:"demand_id"`
	ProjectID uint32    `gorm:"column:project_id;type:int unsigned;primaryKey" json:"project_id"`
	Progress  int32     `gorm:"column:progress;type:int;not null;comment:进度" json:"progress"` // 进度
	CreateAt  time.Time `gorm:"column:create_at;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"create_at"`
}

// TableName CjDemandProject's table name
func (*CjDemandProject) TableName() string {
	return TableNameCjDemandProject
}
