// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCjDepartment = "cj_department"

// CjDepartment 部门
type CjDepartment struct {
	ID    uint32 `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id"`
	Title string `gorm:"column:title;type:varchar(60);not null;comment:名词" json:"title"` // 名词
}

// TableName CjDepartment's table name
func (*CjDepartment) TableName() string {
	return TableNameCjDepartment
}
