// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCjEmployee = "cj_employee"

// CjEmployee 员工
type CjEmployee struct {
	ID        uint32     `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id"`
	Jobnumber string     `gorm:"column:jobnumber;type:varchar(8);not null;uniqueIndex:JOBNUMBER_UNIQUE,priority:1" json:"jobnumber"`
	Username  string     `gorm:"column:username;type:varchar(30);not null;uniqueIndex:USERNAME_UNIQUE,priority:1" json:"username"`
	Password  []byte     `gorm:"column:password;type:binary(32);not null" json:"password"`
	Nickname  *string    `gorm:"column:nickname;type:varchar(30)" json:"nickname"`
	Fullname  *string    `gorm:"column:fullname;type:varchar(200)" json:"fullname"`
	Birthday  *time.Time `gorm:"column:birthday;type:datetime" json:"birthday"`
	IsRemoved uint32     `gorm:"column:is_removed;type:tinyint unsigned;not null" json:"is_removed"`
}

// TableName CjEmployee's table name
func (*CjEmployee) TableName() string {
	return TableNameCjEmployee
}
