// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCjMachineDiskUsage = "cj_machine_disk_usage"

// CjMachineDiskUsage 硬盘使用
type CjMachineDiskUsage struct {
	ID                uint32    `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id"`
	Path              string    `gorm:"column:path;type:varchar(60);not null;index:PATH_INDEX,priority:1" json:"path"`
	Fstype            string    `gorm:"column:fstype;type:varchar(60);not null;index:FSTYPE,priority:1" json:"fstype"`
	Total             uint64    `gorm:"column:total;type:bigint unsigned;not null" json:"total"`
	Free              uint64    `gorm:"column:free;type:bigint unsigned;not null" json:"free"`
	Used              uint64    `gorm:"column:used;type:bigint unsigned;not null" json:"used"`
	UsedPercent       float64   `gorm:"column:used_percent;type:double;not null" json:"used_percent"`
	InodesTotal       uint64    `gorm:"column:inodes_total;type:bigint unsigned;not null" json:"inodes_total"`
	InodesUsed        uint64    `gorm:"column:inodes_used;type:bigint unsigned;not null" json:"inodes_used"`
	InodesFree        uint64    `gorm:"column:inodes_free;type:bigint unsigned;not null" json:"inodes_free"`
	InodesUsedPercent float64   `gorm:"column:inodes_used_percent;type:double;not null" json:"inodes_used_percent"`
	CreateAt          time.Time `gorm:"column:create_at;type:datetime;not null;index:CREATE_AT_INDEX,priority:1;comment:记录时间" json:"create_at"` // 记录时间
}

// TableName CjMachineDiskUsage's table name
func (*CjMachineDiskUsage) TableName() string {
	return TableNameCjMachineDiskUsage
}
