// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCjMachineProcess = "cj_machine_process"

// CjMachineProcess 进程
type CjMachineProcess struct {
	ID         uint32    `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id"`
	Pid        uint32    `gorm:"column:pid;type:int unsigned;not null" json:"pid"`
	Name       string    `gorm:"column:name;type:varchar(60);not null" json:"name"`
	Username   string    `gorm:"column:username;type:varchar(60);not null" json:"username"`
	Cmdline    string    `gorm:"column:cmdline;type:varchar(120);not null" json:"cmdline"`
	Workdir    string    `gorm:"column:workdir;type:varchar(120);not null" json:"workdir"`
	CPUPercent float64   `gorm:"column:cpu_percent;type:double;not null" json:"cpu_percent"`
	MemPercent float32   `gorm:"column:mem_percent;type:float;not null" json:"mem_percent"`
	CreateAt   time.Time `gorm:"column:create_at;type:datetime;not null;index:CREATE_AT_INDEX,priority:1;comment:记录时间" json:"create_at"` // 记录时间
}

// TableName CjMachineProcess's table name
func (*CjMachineProcess) TableName() string {
	return TableNameCjMachineProcess
}
