// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCjMachineVirtualMemory = "cj_machine_virtual_memory"

// CjMachineVirtualMemory 内存
type CjMachineVirtualMemory struct {
	ID             int32     `gorm:"column:id;type:int;primaryKey" json:"id"`
	Total          float32   `gorm:"column:total;type:float;not null;comment:全部" json:"total"` // 全部
	Available      float32   `gorm:"column:available;type:float;not null" json:"available"`
	Used           float32   `gorm:"column:used;type:float;not null;comment:已用" json:"used"` // 已用
	UsedPercent    float32   `gorm:"column:used_percent;type:float;not null" json:"used_percent"`
	Free           float32   `gorm:"column:free;type:float;not null;comment:空闲" json:"free"` // 空闲
	Active         float32   `gorm:"column:active;type:float;not null" json:"active"`
	Inactive       float32   `gorm:"column:inactive;type:float;not null" json:"inactive"`
	Wired          float32   `gorm:"column:wired;type:float;not null" json:"wired"`
	Laundry        float32   `gorm:"column:laundry;type:float;not null" json:"laundry"`
	Buffers        float32   `gorm:"column:buffers;type:float;not null" json:"buffers"`
	Cached         float32   `gorm:"column:cached;type:float;not null" json:"cached"`
	WriteBack      float32   `gorm:"column:write_back;type:float;not null" json:"write_back"`
	Dirty          float32   `gorm:"column:dirty;type:float;not null" json:"dirty"`
	WriteBackTmp   float32   `gorm:"column:write_back_tmp;type:float;not null" json:"write_back_tmp"`
	Shared         float32   `gorm:"column:shared;type:float;not null" json:"shared"`
	Slab           float32   `gorm:"column:slab;type:float;not null" json:"slab"`
	Sreclaimable   float32   `gorm:"column:sreclaimable;type:float;not null" json:"sreclaimable"`
	Sunreclaim     float32   `gorm:"column:sunreclaim;type:float;not null" json:"sunreclaim"`
	PageTables     float32   `gorm:"column:page_tables;type:float;not null" json:"page_tables"`
	SwapCached     float32   `gorm:"column:swap_cached;type:float;not null" json:"swap_cached"`
	CommitLimit    float32   `gorm:"column:commit_limit;type:float;not null" json:"commit_limit"`
	CommittedAs    float32   `gorm:"column:committed_as;type:float;not null" json:"committed_as"`
	HighTotal      float32   `gorm:"column:high_total;type:float;not null" json:"high_total"`
	HighFree       float32   `gorm:"column:high_free;type:float;not null" json:"high_free"`
	LowTotal       float32   `gorm:"column:low_total;type:float;not null" json:"low_total"`
	LowFree        float32   `gorm:"column:low_free;type:float;not null" json:"low_free"`
	SwapTotal      float32   `gorm:"column:swap_total;type:float;not null" json:"swap_total"`
	SwapFree       float32   `gorm:"column:swap_free;type:float;not null" json:"swap_free"`
	Mapped         float32   `gorm:"column:mapped;type:float;not null" json:"mapped"`
	VmallocTotal   float32   `gorm:"column:vmalloc_total;type:float;not null" json:"vmalloc_total"`
	VmallocUsed    float32   `gorm:"column:vmalloc_used;type:float;not null" json:"vmalloc_used"`
	VmallocChunk   float32   `gorm:"column:vmalloc_chunk;type:float;not null" json:"vmalloc_chunk"`
	HugePagesTotal float32   `gorm:"column:huge_pages_total;type:float;not null" json:"huge_pages_total"`
	HugePagesFree  float32   `gorm:"column:huge_pages_free;type:float;not null" json:"huge_pages_free"`
	HugePagesRsvd  float32   `gorm:"column:huge_pages_rsvd;type:float;not null" json:"huge_pages_rsvd"`
	HugePagesSurp  float32   `gorm:"column:huge_pages_surp;type:float;not null" json:"huge_pages_surp"`
	HugePageSize   float32   `gorm:"column:huge_page_size;type:float;not null" json:"huge_page_size"`
	AnonHugePages  float32   `gorm:"column:anon_huge_pages;type:float;not null" json:"anon_huge_pages"`
	CreateAt       time.Time `gorm:"column:create_at;type:datetime;not null;index:CREATE_AT_INDEX,priority:1;comment:记录时间" json:"create_at"` // 记录时间
}

// TableName CjMachineVirtualMemory's table name
func (*CjMachineVirtualMemory) TableName() string {
	return TableNameCjMachineVirtualMemory
}
