// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCjOperation = "cj_operation"

// CjOperation 操作
type CjOperation struct {
	ID           uint32    `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id"`
	OperatorID   uint32    `gorm:"column:operator_id;type:int unsigned;not null;index:OPERATOR_INDEX,priority:1;comment:操作者 ID" json:"operator_id"`                     // 操作者 ID
	OperatorType uint32    `gorm:"column:operator_type;type:tinyint unsigned;not null;index:OPERATOR_INDEX,priority:2;comment:操作者类型" json:"operator_type"`              // 操作者类型
	OperateAt    time.Time `gorm:"column:operate_at;type:datetime;not null;index:OPERATE_AT_INDEX,priority:1;default:CURRENT_TIMESTAMP;comment:操作时间" json:"operate_at"` // 操作时间
	/*
		操作类型:
		0.登录
		1.增
		2.删
		3.改
		4.查
	*/
	OperateType    uint32 `gorm:"column:operate_type;type:tinyint unsigned;not null;index:OPERATE_AT_INDEX,priority:2;comment:操作类型:\n0.登录\n1.增\n2.删\n3.改\n4.查" json:"operate_type"`
	OperateSummary string `gorm:"column:operate_summary;type:varchar(120);not null;comment:操作概要" json:"operate_summary"` // 操作概要
}

// TableName CjOperation's table name
func (*CjOperation) TableName() string {
	return TableNameCjOperation
}
