// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCjProjectEmployee = "cj_project_employee"

// CjProjectEmployee mapped from table <cj_project_employee>
type CjProjectEmployee struct {
	ID         uint32 `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id"`
	ProjectID  uint32 `gorm:"column:project_id;type:int unsigned;not null;index:PROJECT_EMPLOYEE_UNIQUE,priority:1;comment:项目ID" json:"project_id"`   // 项目ID
	EmployeeID uint32 `gorm:"column:employee_id;type:int unsigned;not null;index:PROJECT_EMPLOYEE_UNIQUE,priority:2;comment:员工ID" json:"employee_id"` // 员工ID
}

// TableName CjProjectEmployee's table name
func (*CjProjectEmployee) TableName() string {
	return TableNameCjProjectEmployee
}
