// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCjProject = "cj_project"

// CjProject 项目
type CjProject struct {
	ID   uint32 `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id"`
	Name string `gorm:"column:name;type:varchar(60);not null;comment:项目名" json:"name"` // 项目名
}

// TableName CjProject's table name
func (*CjProject) TableName() string {
	return TableNameCjProject
}
