// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCjPermission = "cj_permission"

// CjPermission 权限
type CjPermission struct {
	ID          uint32  `gorm:"column:id;type:int unsigned;primaryKey" json:"id"`
	ParentID    uint32  `gorm:"column:parent_id;type:int unsigned;not null" json:"parent_id"`
	Tag         string  `gorm:"column:tag;type:varchar(60);not null;uniqueIndex:TAG_UNIQUE,priority:1" json:"tag"`
	Title       string  `gorm:"column:title;type:varchar(60);not null" json:"title"`
	Level       uint32  `gorm:"column:level;type:tinyint unsigned;not null" json:"level"`
	Description *string `gorm:"column:description;type:text" json:"description"`
}

// TableName CjPermission's table name
func (*CjPermission) TableName() string {
	return TableNameCjPermission
}
