// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCjProjectEmployee = "cj_project_employee"

// CjProjectEmployee mapped from table <cj_project_employee>
type CjProjectEmployee struct {
	ProjectID  uint32    `gorm:"column:project_id;type:int unsigned;primaryKey;comment:项目ID" json:"project_id"`   // 项目ID
	EmployeeID uint32    `gorm:"column:employee_id;type:int unsigned;primaryKey;comment:员工ID" json:"employee_id"` // 员工ID
	CreateAt   time.Time `gorm:"column:create_at;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"create_at"`
}

// TableName CjProjectEmployee's table name
func (*CjProjectEmployee) TableName() string {
	return TableNameCjProjectEmployee
}
