// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCjScript = "cj_script"

// CjScript 脚本
type CjScript struct {
	ID        uint32 `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	PassID    uint32 `gorm:"column:pass_id;type:int unsigned;not null;comment:密钥ID" json:"pass_id"`          // 密钥ID
	ProjectID uint32 `gorm:"column:project_id;type:int unsigned;not null;comment:项目ID" json:"project_id"`    // 项目ID
	Title     string `gorm:"column:title;type:varchar(60);not null;comment:标题" json:"title"`                 // 标题
	Content   string `gorm:"column:content;type:text;not null;comment:内容" json:"content"`                    // 内容
}

// TableName CjScript's table name
func (*CjScript) TableName() string {
	return TableNameCjScript
}
