// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/cjungo/cjuncms/model"
)

func newCjDemandEmployee(db *gorm.DB, opts ...gen.DOOption) cjDemandEmployee {
	_cjDemandEmployee := cjDemandEmployee{}

	_cjDemandEmployee.cjDemandEmployeeDo.UseDB(db, opts...)
	_cjDemandEmployee.cjDemandEmployeeDo.UseModel(&model.CjDemandEmployee{})

	tableName := _cjDemandEmployee.cjDemandEmployeeDo.TableName()
	_cjDemandEmployee.ALL = field.NewAsterisk(tableName)
	_cjDemandEmployee.DemandID = field.NewUint32(tableName, "demand_id")
	_cjDemandEmployee.EmployeeID = field.NewUint32(tableName, "employee_id")
	_cjDemandEmployee.CreateAt = field.NewTime(tableName, "create_at")

	_cjDemandEmployee.fillFieldMap()

	return _cjDemandEmployee
}

type cjDemandEmployee struct {
	cjDemandEmployeeDo cjDemandEmployeeDo

	ALL        field.Asterisk
	DemandID   field.Uint32
	EmployeeID field.Uint32
	CreateAt   field.Time

	fieldMap map[string]field.Expr
}

func (c cjDemandEmployee) Table(newTableName string) *cjDemandEmployee {
	c.cjDemandEmployeeDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c cjDemandEmployee) As(alias string) *cjDemandEmployee {
	c.cjDemandEmployeeDo.DO = *(c.cjDemandEmployeeDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *cjDemandEmployee) updateTableName(table string) *cjDemandEmployee {
	c.ALL = field.NewAsterisk(table)
	c.DemandID = field.NewUint32(table, "demand_id")
	c.EmployeeID = field.NewUint32(table, "employee_id")
	c.CreateAt = field.NewTime(table, "create_at")

	c.fillFieldMap()

	return c
}

func (c *cjDemandEmployee) WithContext(ctx context.Context) *cjDemandEmployeeDo {
	return c.cjDemandEmployeeDo.WithContext(ctx)
}

func (c cjDemandEmployee) TableName() string { return c.cjDemandEmployeeDo.TableName() }

func (c cjDemandEmployee) Alias() string { return c.cjDemandEmployeeDo.Alias() }

func (c cjDemandEmployee) Columns(cols ...field.Expr) gen.Columns {
	return c.cjDemandEmployeeDo.Columns(cols...)
}

func (c *cjDemandEmployee) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *cjDemandEmployee) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 3)
	c.fieldMap["demand_id"] = c.DemandID
	c.fieldMap["employee_id"] = c.EmployeeID
	c.fieldMap["create_at"] = c.CreateAt
}

func (c cjDemandEmployee) clone(db *gorm.DB) cjDemandEmployee {
	c.cjDemandEmployeeDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c cjDemandEmployee) replaceDB(db *gorm.DB) cjDemandEmployee {
	c.cjDemandEmployeeDo.ReplaceDB(db)
	return c
}

type cjDemandEmployeeDo struct{ gen.DO }

func (c cjDemandEmployeeDo) Debug() *cjDemandEmployeeDo {
	return c.withDO(c.DO.Debug())
}

func (c cjDemandEmployeeDo) WithContext(ctx context.Context) *cjDemandEmployeeDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c cjDemandEmployeeDo) ReadDB() *cjDemandEmployeeDo {
	return c.Clauses(dbresolver.Read)
}

func (c cjDemandEmployeeDo) WriteDB() *cjDemandEmployeeDo {
	return c.Clauses(dbresolver.Write)
}

func (c cjDemandEmployeeDo) Session(config *gorm.Session) *cjDemandEmployeeDo {
	return c.withDO(c.DO.Session(config))
}

func (c cjDemandEmployeeDo) Clauses(conds ...clause.Expression) *cjDemandEmployeeDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c cjDemandEmployeeDo) Returning(value interface{}, columns ...string) *cjDemandEmployeeDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c cjDemandEmployeeDo) Not(conds ...gen.Condition) *cjDemandEmployeeDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c cjDemandEmployeeDo) Or(conds ...gen.Condition) *cjDemandEmployeeDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c cjDemandEmployeeDo) Select(conds ...field.Expr) *cjDemandEmployeeDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c cjDemandEmployeeDo) Where(conds ...gen.Condition) *cjDemandEmployeeDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c cjDemandEmployeeDo) Order(conds ...field.Expr) *cjDemandEmployeeDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c cjDemandEmployeeDo) Distinct(cols ...field.Expr) *cjDemandEmployeeDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c cjDemandEmployeeDo) Omit(cols ...field.Expr) *cjDemandEmployeeDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c cjDemandEmployeeDo) Join(table schema.Tabler, on ...field.Expr) *cjDemandEmployeeDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c cjDemandEmployeeDo) LeftJoin(table schema.Tabler, on ...field.Expr) *cjDemandEmployeeDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c cjDemandEmployeeDo) RightJoin(table schema.Tabler, on ...field.Expr) *cjDemandEmployeeDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c cjDemandEmployeeDo) Group(cols ...field.Expr) *cjDemandEmployeeDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c cjDemandEmployeeDo) Having(conds ...gen.Condition) *cjDemandEmployeeDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c cjDemandEmployeeDo) Limit(limit int) *cjDemandEmployeeDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c cjDemandEmployeeDo) Offset(offset int) *cjDemandEmployeeDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c cjDemandEmployeeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *cjDemandEmployeeDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c cjDemandEmployeeDo) Unscoped() *cjDemandEmployeeDo {
	return c.withDO(c.DO.Unscoped())
}

func (c cjDemandEmployeeDo) Create(values ...*model.CjDemandEmployee) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c cjDemandEmployeeDo) CreateInBatches(values []*model.CjDemandEmployee, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c cjDemandEmployeeDo) Save(values ...*model.CjDemandEmployee) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c cjDemandEmployeeDo) First() (*model.CjDemandEmployee, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.CjDemandEmployee), nil
	}
}

func (c cjDemandEmployeeDo) Take() (*model.CjDemandEmployee, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.CjDemandEmployee), nil
	}
}

func (c cjDemandEmployeeDo) Last() (*model.CjDemandEmployee, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.CjDemandEmployee), nil
	}
}

func (c cjDemandEmployeeDo) Find() ([]*model.CjDemandEmployee, error) {
	result, err := c.DO.Find()
	return result.([]*model.CjDemandEmployee), err
}

func (c cjDemandEmployeeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CjDemandEmployee, err error) {
	buf := make([]*model.CjDemandEmployee, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c cjDemandEmployeeDo) FindInBatches(result *[]*model.CjDemandEmployee, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c cjDemandEmployeeDo) Attrs(attrs ...field.AssignExpr) *cjDemandEmployeeDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c cjDemandEmployeeDo) Assign(attrs ...field.AssignExpr) *cjDemandEmployeeDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c cjDemandEmployeeDo) Joins(fields ...field.RelationField) *cjDemandEmployeeDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c cjDemandEmployeeDo) Preload(fields ...field.RelationField) *cjDemandEmployeeDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c cjDemandEmployeeDo) FirstOrInit() (*model.CjDemandEmployee, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.CjDemandEmployee), nil
	}
}

func (c cjDemandEmployeeDo) FirstOrCreate() (*model.CjDemandEmployee, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.CjDemandEmployee), nil
	}
}

func (c cjDemandEmployeeDo) FindByPage(offset int, limit int) (result []*model.CjDemandEmployee, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c cjDemandEmployeeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c cjDemandEmployeeDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c cjDemandEmployeeDo) Delete(models ...*model.CjDemandEmployee) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *cjDemandEmployeeDo) withDO(do gen.Dao) *cjDemandEmployeeDo {
	c.DO = *do.(*gen.DO)
	return c
}
