// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/cjungo/cjuncms/model"
)

func newCjDemand(db *gorm.DB, opts ...gen.DOOption) cjDemand {
	_cjDemand := cjDemand{}

	_cjDemand.cjDemandDo.UseDB(db, opts...)
	_cjDemand.cjDemandDo.UseModel(&model.CjDemand{})

	tableName := _cjDemand.cjDemandDo.TableName()
	_cjDemand.ALL = field.NewAsterisk(tableName)
	_cjDemand.ID = field.NewUint32(tableName, "id")
	_cjDemand.Title = field.NewString(tableName, "title")
	_cjDemand.Content = field.NewString(tableName, "content")
	_cjDemand.CreateAt = field.NewTime(tableName, "create_at")

	_cjDemand.fillFieldMap()

	return _cjDemand
}

// cjDemand 需求
type cjDemand struct {
	cjDemandDo cjDemandDo

	ALL      field.Asterisk
	ID       field.Uint32
	Title    field.String // 标题
	Content  field.String // 内容
	CreateAt field.Time

	fieldMap map[string]field.Expr
}

func (c cjDemand) Table(newTableName string) *cjDemand {
	c.cjDemandDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c cjDemand) As(alias string) *cjDemand {
	c.cjDemandDo.DO = *(c.cjDemandDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *cjDemand) updateTableName(table string) *cjDemand {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewUint32(table, "id")
	c.Title = field.NewString(table, "title")
	c.Content = field.NewString(table, "content")
	c.CreateAt = field.NewTime(table, "create_at")

	c.fillFieldMap()

	return c
}

func (c *cjDemand) WithContext(ctx context.Context) *cjDemandDo { return c.cjDemandDo.WithContext(ctx) }

func (c cjDemand) TableName() string { return c.cjDemandDo.TableName() }

func (c cjDemand) Alias() string { return c.cjDemandDo.Alias() }

func (c cjDemand) Columns(cols ...field.Expr) gen.Columns { return c.cjDemandDo.Columns(cols...) }

func (c *cjDemand) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *cjDemand) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 4)
	c.fieldMap["id"] = c.ID
	c.fieldMap["title"] = c.Title
	c.fieldMap["content"] = c.Content
	c.fieldMap["create_at"] = c.CreateAt
}

func (c cjDemand) clone(db *gorm.DB) cjDemand {
	c.cjDemandDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c cjDemand) replaceDB(db *gorm.DB) cjDemand {
	c.cjDemandDo.ReplaceDB(db)
	return c
}

type cjDemandDo struct{ gen.DO }

func (c cjDemandDo) Debug() *cjDemandDo {
	return c.withDO(c.DO.Debug())
}

func (c cjDemandDo) WithContext(ctx context.Context) *cjDemandDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c cjDemandDo) ReadDB() *cjDemandDo {
	return c.Clauses(dbresolver.Read)
}

func (c cjDemandDo) WriteDB() *cjDemandDo {
	return c.Clauses(dbresolver.Write)
}

func (c cjDemandDo) Session(config *gorm.Session) *cjDemandDo {
	return c.withDO(c.DO.Session(config))
}

func (c cjDemandDo) Clauses(conds ...clause.Expression) *cjDemandDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c cjDemandDo) Returning(value interface{}, columns ...string) *cjDemandDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c cjDemandDo) Not(conds ...gen.Condition) *cjDemandDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c cjDemandDo) Or(conds ...gen.Condition) *cjDemandDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c cjDemandDo) Select(conds ...field.Expr) *cjDemandDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c cjDemandDo) Where(conds ...gen.Condition) *cjDemandDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c cjDemandDo) Order(conds ...field.Expr) *cjDemandDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c cjDemandDo) Distinct(cols ...field.Expr) *cjDemandDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c cjDemandDo) Omit(cols ...field.Expr) *cjDemandDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c cjDemandDo) Join(table schema.Tabler, on ...field.Expr) *cjDemandDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c cjDemandDo) LeftJoin(table schema.Tabler, on ...field.Expr) *cjDemandDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c cjDemandDo) RightJoin(table schema.Tabler, on ...field.Expr) *cjDemandDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c cjDemandDo) Group(cols ...field.Expr) *cjDemandDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c cjDemandDo) Having(conds ...gen.Condition) *cjDemandDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c cjDemandDo) Limit(limit int) *cjDemandDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c cjDemandDo) Offset(offset int) *cjDemandDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c cjDemandDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *cjDemandDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c cjDemandDo) Unscoped() *cjDemandDo {
	return c.withDO(c.DO.Unscoped())
}

func (c cjDemandDo) Create(values ...*model.CjDemand) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c cjDemandDo) CreateInBatches(values []*model.CjDemand, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c cjDemandDo) Save(values ...*model.CjDemand) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c cjDemandDo) First() (*model.CjDemand, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.CjDemand), nil
	}
}

func (c cjDemandDo) Take() (*model.CjDemand, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.CjDemand), nil
	}
}

func (c cjDemandDo) Last() (*model.CjDemand, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.CjDemand), nil
	}
}

func (c cjDemandDo) Find() ([]*model.CjDemand, error) {
	result, err := c.DO.Find()
	return result.([]*model.CjDemand), err
}

func (c cjDemandDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CjDemand, err error) {
	buf := make([]*model.CjDemand, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c cjDemandDo) FindInBatches(result *[]*model.CjDemand, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c cjDemandDo) Attrs(attrs ...field.AssignExpr) *cjDemandDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c cjDemandDo) Assign(attrs ...field.AssignExpr) *cjDemandDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c cjDemandDo) Joins(fields ...field.RelationField) *cjDemandDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c cjDemandDo) Preload(fields ...field.RelationField) *cjDemandDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c cjDemandDo) FirstOrInit() (*model.CjDemand, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.CjDemand), nil
	}
}

func (c cjDemandDo) FirstOrCreate() (*model.CjDemand, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.CjDemand), nil
	}
}

func (c cjDemandDo) FindByPage(offset int, limit int) (result []*model.CjDemand, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c cjDemandDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c cjDemandDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c cjDemandDo) Delete(models ...*model.CjDemand) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *cjDemandDo) withDO(do gen.Dao) *cjDemandDo {
	c.DO = *do.(*gen.DO)
	return c
}
