// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/cjungo/cjuncms/model"
)

func newCjDepartmentEmployee(db *gorm.DB, opts ...gen.DOOption) cjDepartmentEmployee {
	_cjDepartmentEmployee := cjDepartmentEmployee{}

	_cjDepartmentEmployee.cjDepartmentEmployeeDo.UseDB(db, opts...)
	_cjDepartmentEmployee.cjDepartmentEmployeeDo.UseModel(&model.CjDepartmentEmployee{})

	tableName := _cjDepartmentEmployee.cjDepartmentEmployeeDo.TableName()
	_cjDepartmentEmployee.ALL = field.NewAsterisk(tableName)
	_cjDepartmentEmployee.DepartmentID = field.NewUint32(tableName, "department_id")
	_cjDepartmentEmployee.EmployeeID = field.NewUint32(tableName, "employee_id")
	_cjDepartmentEmployee.PositionID = field.NewUint32(tableName, "position_id")
	_cjDepartmentEmployee.CreateAt = field.NewTime(tableName, "create_at")

	_cjDepartmentEmployee.fillFieldMap()

	return _cjDepartmentEmployee
}

type cjDepartmentEmployee struct {
	cjDepartmentEmployeeDo cjDepartmentEmployeeDo

	ALL          field.Asterisk
	DepartmentID field.Uint32
	EmployeeID   field.Uint32
	PositionID   field.Uint32
	CreateAt     field.Time

	fieldMap map[string]field.Expr
}

func (c cjDepartmentEmployee) Table(newTableName string) *cjDepartmentEmployee {
	c.cjDepartmentEmployeeDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c cjDepartmentEmployee) As(alias string) *cjDepartmentEmployee {
	c.cjDepartmentEmployeeDo.DO = *(c.cjDepartmentEmployeeDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *cjDepartmentEmployee) updateTableName(table string) *cjDepartmentEmployee {
	c.ALL = field.NewAsterisk(table)
	c.DepartmentID = field.NewUint32(table, "department_id")
	c.EmployeeID = field.NewUint32(table, "employee_id")
	c.PositionID = field.NewUint32(table, "position_id")
	c.CreateAt = field.NewTime(table, "create_at")

	c.fillFieldMap()

	return c
}

func (c *cjDepartmentEmployee) WithContext(ctx context.Context) *cjDepartmentEmployeeDo {
	return c.cjDepartmentEmployeeDo.WithContext(ctx)
}

func (c cjDepartmentEmployee) TableName() string { return c.cjDepartmentEmployeeDo.TableName() }

func (c cjDepartmentEmployee) Alias() string { return c.cjDepartmentEmployeeDo.Alias() }

func (c cjDepartmentEmployee) Columns(cols ...field.Expr) gen.Columns {
	return c.cjDepartmentEmployeeDo.Columns(cols...)
}

func (c *cjDepartmentEmployee) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *cjDepartmentEmployee) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 4)
	c.fieldMap["department_id"] = c.DepartmentID
	c.fieldMap["employee_id"] = c.EmployeeID
	c.fieldMap["position_id"] = c.PositionID
	c.fieldMap["create_at"] = c.CreateAt
}

func (c cjDepartmentEmployee) clone(db *gorm.DB) cjDepartmentEmployee {
	c.cjDepartmentEmployeeDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c cjDepartmentEmployee) replaceDB(db *gorm.DB) cjDepartmentEmployee {
	c.cjDepartmentEmployeeDo.ReplaceDB(db)
	return c
}

type cjDepartmentEmployeeDo struct{ gen.DO }

func (c cjDepartmentEmployeeDo) Debug() *cjDepartmentEmployeeDo {
	return c.withDO(c.DO.Debug())
}

func (c cjDepartmentEmployeeDo) WithContext(ctx context.Context) *cjDepartmentEmployeeDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c cjDepartmentEmployeeDo) ReadDB() *cjDepartmentEmployeeDo {
	return c.Clauses(dbresolver.Read)
}

func (c cjDepartmentEmployeeDo) WriteDB() *cjDepartmentEmployeeDo {
	return c.Clauses(dbresolver.Write)
}

func (c cjDepartmentEmployeeDo) Session(config *gorm.Session) *cjDepartmentEmployeeDo {
	return c.withDO(c.DO.Session(config))
}

func (c cjDepartmentEmployeeDo) Clauses(conds ...clause.Expression) *cjDepartmentEmployeeDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c cjDepartmentEmployeeDo) Returning(value interface{}, columns ...string) *cjDepartmentEmployeeDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c cjDepartmentEmployeeDo) Not(conds ...gen.Condition) *cjDepartmentEmployeeDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c cjDepartmentEmployeeDo) Or(conds ...gen.Condition) *cjDepartmentEmployeeDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c cjDepartmentEmployeeDo) Select(conds ...field.Expr) *cjDepartmentEmployeeDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c cjDepartmentEmployeeDo) Where(conds ...gen.Condition) *cjDepartmentEmployeeDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c cjDepartmentEmployeeDo) Order(conds ...field.Expr) *cjDepartmentEmployeeDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c cjDepartmentEmployeeDo) Distinct(cols ...field.Expr) *cjDepartmentEmployeeDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c cjDepartmentEmployeeDo) Omit(cols ...field.Expr) *cjDepartmentEmployeeDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c cjDepartmentEmployeeDo) Join(table schema.Tabler, on ...field.Expr) *cjDepartmentEmployeeDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c cjDepartmentEmployeeDo) LeftJoin(table schema.Tabler, on ...field.Expr) *cjDepartmentEmployeeDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c cjDepartmentEmployeeDo) RightJoin(table schema.Tabler, on ...field.Expr) *cjDepartmentEmployeeDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c cjDepartmentEmployeeDo) Group(cols ...field.Expr) *cjDepartmentEmployeeDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c cjDepartmentEmployeeDo) Having(conds ...gen.Condition) *cjDepartmentEmployeeDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c cjDepartmentEmployeeDo) Limit(limit int) *cjDepartmentEmployeeDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c cjDepartmentEmployeeDo) Offset(offset int) *cjDepartmentEmployeeDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c cjDepartmentEmployeeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *cjDepartmentEmployeeDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c cjDepartmentEmployeeDo) Unscoped() *cjDepartmentEmployeeDo {
	return c.withDO(c.DO.Unscoped())
}

func (c cjDepartmentEmployeeDo) Create(values ...*model.CjDepartmentEmployee) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c cjDepartmentEmployeeDo) CreateInBatches(values []*model.CjDepartmentEmployee, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c cjDepartmentEmployeeDo) Save(values ...*model.CjDepartmentEmployee) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c cjDepartmentEmployeeDo) First() (*model.CjDepartmentEmployee, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.CjDepartmentEmployee), nil
	}
}

func (c cjDepartmentEmployeeDo) Take() (*model.CjDepartmentEmployee, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.CjDepartmentEmployee), nil
	}
}

func (c cjDepartmentEmployeeDo) Last() (*model.CjDepartmentEmployee, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.CjDepartmentEmployee), nil
	}
}

func (c cjDepartmentEmployeeDo) Find() ([]*model.CjDepartmentEmployee, error) {
	result, err := c.DO.Find()
	return result.([]*model.CjDepartmentEmployee), err
}

func (c cjDepartmentEmployeeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CjDepartmentEmployee, err error) {
	buf := make([]*model.CjDepartmentEmployee, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c cjDepartmentEmployeeDo) FindInBatches(result *[]*model.CjDepartmentEmployee, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c cjDepartmentEmployeeDo) Attrs(attrs ...field.AssignExpr) *cjDepartmentEmployeeDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c cjDepartmentEmployeeDo) Assign(attrs ...field.AssignExpr) *cjDepartmentEmployeeDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c cjDepartmentEmployeeDo) Joins(fields ...field.RelationField) *cjDepartmentEmployeeDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c cjDepartmentEmployeeDo) Preload(fields ...field.RelationField) *cjDepartmentEmployeeDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c cjDepartmentEmployeeDo) FirstOrInit() (*model.CjDepartmentEmployee, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.CjDepartmentEmployee), nil
	}
}

func (c cjDepartmentEmployeeDo) FirstOrCreate() (*model.CjDepartmentEmployee, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.CjDepartmentEmployee), nil
	}
}

func (c cjDepartmentEmployeeDo) FindByPage(offset int, limit int) (result []*model.CjDepartmentEmployee, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c cjDepartmentEmployeeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c cjDepartmentEmployeeDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c cjDepartmentEmployeeDo) Delete(models ...*model.CjDepartmentEmployee) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *cjDepartmentEmployeeDo) withDO(do gen.Dao) *cjDepartmentEmployeeDo {
	c.DO = *do.(*gen.DO)
	return c
}
