// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/cjungo/cjuncms/model"
)

func newCjDemandProject(db *gorm.DB, opts ...gen.DOOption) cjDemandProject {
	_cjDemandProject := cjDemandProject{}

	_cjDemandProject.cjDemandProjectDo.UseDB(db, opts...)
	_cjDemandProject.cjDemandProjectDo.UseModel(&model.CjDemandProject{})

	tableName := _cjDemandProject.cjDemandProjectDo.TableName()
	_cjDemandProject.ALL = field.NewAsterisk(tableName)
	_cjDemandProject.DemandID = field.NewUint32(tableName, "demand_id")
	_cjDemandProject.ProjectID = field.NewUint32(tableName, "project_id")
	_cjDemandProject.Progress = field.NewInt32(tableName, "progress")
	_cjDemandProject.CreateAt = field.NewTime(tableName, "create_at")

	_cjDemandProject.fillFieldMap()

	return _cjDemandProject
}

type cjDemandProject struct {
	cjDemandProjectDo cjDemandProjectDo

	ALL       field.Asterisk
	DemandID  field.Uint32
	ProjectID field.Uint32
	Progress  field.Int32 // 进度
	CreateAt  field.Time

	fieldMap map[string]field.Expr
}

func (c cjDemandProject) Table(newTableName string) *cjDemandProject {
	c.cjDemandProjectDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c cjDemandProject) As(alias string) *cjDemandProject {
	c.cjDemandProjectDo.DO = *(c.cjDemandProjectDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *cjDemandProject) updateTableName(table string) *cjDemandProject {
	c.ALL = field.NewAsterisk(table)
	c.DemandID = field.NewUint32(table, "demand_id")
	c.ProjectID = field.NewUint32(table, "project_id")
	c.Progress = field.NewInt32(table, "progress")
	c.CreateAt = field.NewTime(table, "create_at")

	c.fillFieldMap()

	return c
}

func (c *cjDemandProject) WithContext(ctx context.Context) *cjDemandProjectDo {
	return c.cjDemandProjectDo.WithContext(ctx)
}

func (c cjDemandProject) TableName() string { return c.cjDemandProjectDo.TableName() }

func (c cjDemandProject) Alias() string { return c.cjDemandProjectDo.Alias() }

func (c cjDemandProject) Columns(cols ...field.Expr) gen.Columns {
	return c.cjDemandProjectDo.Columns(cols...)
}

func (c *cjDemandProject) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *cjDemandProject) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 4)
	c.fieldMap["demand_id"] = c.DemandID
	c.fieldMap["project_id"] = c.ProjectID
	c.fieldMap["progress"] = c.Progress
	c.fieldMap["create_at"] = c.CreateAt
}

func (c cjDemandProject) clone(db *gorm.DB) cjDemandProject {
	c.cjDemandProjectDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c cjDemandProject) replaceDB(db *gorm.DB) cjDemandProject {
	c.cjDemandProjectDo.ReplaceDB(db)
	return c
}

type cjDemandProjectDo struct{ gen.DO }

func (c cjDemandProjectDo) Debug() *cjDemandProjectDo {
	return c.withDO(c.DO.Debug())
}

func (c cjDemandProjectDo) WithContext(ctx context.Context) *cjDemandProjectDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c cjDemandProjectDo) ReadDB() *cjDemandProjectDo {
	return c.Clauses(dbresolver.Read)
}

func (c cjDemandProjectDo) WriteDB() *cjDemandProjectDo {
	return c.Clauses(dbresolver.Write)
}

func (c cjDemandProjectDo) Session(config *gorm.Session) *cjDemandProjectDo {
	return c.withDO(c.DO.Session(config))
}

func (c cjDemandProjectDo) Clauses(conds ...clause.Expression) *cjDemandProjectDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c cjDemandProjectDo) Returning(value interface{}, columns ...string) *cjDemandProjectDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c cjDemandProjectDo) Not(conds ...gen.Condition) *cjDemandProjectDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c cjDemandProjectDo) Or(conds ...gen.Condition) *cjDemandProjectDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c cjDemandProjectDo) Select(conds ...field.Expr) *cjDemandProjectDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c cjDemandProjectDo) Where(conds ...gen.Condition) *cjDemandProjectDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c cjDemandProjectDo) Order(conds ...field.Expr) *cjDemandProjectDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c cjDemandProjectDo) Distinct(cols ...field.Expr) *cjDemandProjectDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c cjDemandProjectDo) Omit(cols ...field.Expr) *cjDemandProjectDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c cjDemandProjectDo) Join(table schema.Tabler, on ...field.Expr) *cjDemandProjectDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c cjDemandProjectDo) LeftJoin(table schema.Tabler, on ...field.Expr) *cjDemandProjectDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c cjDemandProjectDo) RightJoin(table schema.Tabler, on ...field.Expr) *cjDemandProjectDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c cjDemandProjectDo) Group(cols ...field.Expr) *cjDemandProjectDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c cjDemandProjectDo) Having(conds ...gen.Condition) *cjDemandProjectDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c cjDemandProjectDo) Limit(limit int) *cjDemandProjectDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c cjDemandProjectDo) Offset(offset int) *cjDemandProjectDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c cjDemandProjectDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *cjDemandProjectDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c cjDemandProjectDo) Unscoped() *cjDemandProjectDo {
	return c.withDO(c.DO.Unscoped())
}

func (c cjDemandProjectDo) Create(values ...*model.CjDemandProject) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c cjDemandProjectDo) CreateInBatches(values []*model.CjDemandProject, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c cjDemandProjectDo) Save(values ...*model.CjDemandProject) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c cjDemandProjectDo) First() (*model.CjDemandProject, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.CjDemandProject), nil
	}
}

func (c cjDemandProjectDo) Take() (*model.CjDemandProject, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.CjDemandProject), nil
	}
}

func (c cjDemandProjectDo) Last() (*model.CjDemandProject, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.CjDemandProject), nil
	}
}

func (c cjDemandProjectDo) Find() ([]*model.CjDemandProject, error) {
	result, err := c.DO.Find()
	return result.([]*model.CjDemandProject), err
}

func (c cjDemandProjectDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CjDemandProject, err error) {
	buf := make([]*model.CjDemandProject, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c cjDemandProjectDo) FindInBatches(result *[]*model.CjDemandProject, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c cjDemandProjectDo) Attrs(attrs ...field.AssignExpr) *cjDemandProjectDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c cjDemandProjectDo) Assign(attrs ...field.AssignExpr) *cjDemandProjectDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c cjDemandProjectDo) Joins(fields ...field.RelationField) *cjDemandProjectDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c cjDemandProjectDo) Preload(fields ...field.RelationField) *cjDemandProjectDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c cjDemandProjectDo) FirstOrInit() (*model.CjDemandProject, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.CjDemandProject), nil
	}
}

func (c cjDemandProjectDo) FirstOrCreate() (*model.CjDemandProject, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.CjDemandProject), nil
	}
}

func (c cjDemandProjectDo) FindByPage(offset int, limit int) (result []*model.CjDemandProject, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c cjDemandProjectDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c cjDemandProjectDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c cjDemandProjectDo) Delete(models ...*model.CjDemandProject) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *cjDemandProjectDo) withDO(do gen.Dao) *cjDemandProjectDo {
	c.DO = *do.(*gen.DO)
	return c
}
