// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/cjungo/cjuncms/model"
)

func newCjDepartment(db *gorm.DB, opts ...gen.DOOption) cjDepartment {
	_cjDepartment := cjDepartment{}

	_cjDepartment.cjDepartmentDo.UseDB(db, opts...)
	_cjDepartment.cjDepartmentDo.UseModel(&model.CjDepartment{})

	tableName := _cjDepartment.cjDepartmentDo.TableName()
	_cjDepartment.ALL = field.NewAsterisk(tableName)
	_cjDepartment.ID = field.NewUint32(tableName, "id")
	_cjDepartment.ParentID = field.NewUint32(tableName, "parent_id")
	_cjDepartment.Title = field.NewString(tableName, "title")
	_cjDepartment.CreateAt = field.NewTime(tableName, "create_at")

	_cjDepartment.fillFieldMap()

	return _cjDepartment
}

// cjDepartment 部门
type cjDepartment struct {
	cjDepartmentDo cjDepartmentDo

	ALL      field.Asterisk
	ID       field.Uint32
	ParentID field.Uint32
	Title    field.String // 名称
	CreateAt field.Time

	fieldMap map[string]field.Expr
}

func (c cjDepartment) Table(newTableName string) *cjDepartment {
	c.cjDepartmentDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c cjDepartment) As(alias string) *cjDepartment {
	c.cjDepartmentDo.DO = *(c.cjDepartmentDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *cjDepartment) updateTableName(table string) *cjDepartment {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewUint32(table, "id")
	c.ParentID = field.NewUint32(table, "parent_id")
	c.Title = field.NewString(table, "title")
	c.CreateAt = field.NewTime(table, "create_at")

	c.fillFieldMap()

	return c
}

func (c *cjDepartment) WithContext(ctx context.Context) *cjDepartmentDo {
	return c.cjDepartmentDo.WithContext(ctx)
}

func (c cjDepartment) TableName() string { return c.cjDepartmentDo.TableName() }

func (c cjDepartment) Alias() string { return c.cjDepartmentDo.Alias() }

func (c cjDepartment) Columns(cols ...field.Expr) gen.Columns {
	return c.cjDepartmentDo.Columns(cols...)
}

func (c *cjDepartment) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *cjDepartment) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 4)
	c.fieldMap["id"] = c.ID
	c.fieldMap["parent_id"] = c.ParentID
	c.fieldMap["title"] = c.Title
	c.fieldMap["create_at"] = c.CreateAt
}

func (c cjDepartment) clone(db *gorm.DB) cjDepartment {
	c.cjDepartmentDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c cjDepartment) replaceDB(db *gorm.DB) cjDepartment {
	c.cjDepartmentDo.ReplaceDB(db)
	return c
}

type cjDepartmentDo struct{ gen.DO }

func (c cjDepartmentDo) Debug() *cjDepartmentDo {
	return c.withDO(c.DO.Debug())
}

func (c cjDepartmentDo) WithContext(ctx context.Context) *cjDepartmentDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c cjDepartmentDo) ReadDB() *cjDepartmentDo {
	return c.Clauses(dbresolver.Read)
}

func (c cjDepartmentDo) WriteDB() *cjDepartmentDo {
	return c.Clauses(dbresolver.Write)
}

func (c cjDepartmentDo) Session(config *gorm.Session) *cjDepartmentDo {
	return c.withDO(c.DO.Session(config))
}

func (c cjDepartmentDo) Clauses(conds ...clause.Expression) *cjDepartmentDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c cjDepartmentDo) Returning(value interface{}, columns ...string) *cjDepartmentDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c cjDepartmentDo) Not(conds ...gen.Condition) *cjDepartmentDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c cjDepartmentDo) Or(conds ...gen.Condition) *cjDepartmentDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c cjDepartmentDo) Select(conds ...field.Expr) *cjDepartmentDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c cjDepartmentDo) Where(conds ...gen.Condition) *cjDepartmentDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c cjDepartmentDo) Order(conds ...field.Expr) *cjDepartmentDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c cjDepartmentDo) Distinct(cols ...field.Expr) *cjDepartmentDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c cjDepartmentDo) Omit(cols ...field.Expr) *cjDepartmentDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c cjDepartmentDo) Join(table schema.Tabler, on ...field.Expr) *cjDepartmentDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c cjDepartmentDo) LeftJoin(table schema.Tabler, on ...field.Expr) *cjDepartmentDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c cjDepartmentDo) RightJoin(table schema.Tabler, on ...field.Expr) *cjDepartmentDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c cjDepartmentDo) Group(cols ...field.Expr) *cjDepartmentDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c cjDepartmentDo) Having(conds ...gen.Condition) *cjDepartmentDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c cjDepartmentDo) Limit(limit int) *cjDepartmentDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c cjDepartmentDo) Offset(offset int) *cjDepartmentDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c cjDepartmentDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *cjDepartmentDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c cjDepartmentDo) Unscoped() *cjDepartmentDo {
	return c.withDO(c.DO.Unscoped())
}

func (c cjDepartmentDo) Create(values ...*model.CjDepartment) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c cjDepartmentDo) CreateInBatches(values []*model.CjDepartment, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c cjDepartmentDo) Save(values ...*model.CjDepartment) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c cjDepartmentDo) First() (*model.CjDepartment, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.CjDepartment), nil
	}
}

func (c cjDepartmentDo) Take() (*model.CjDepartment, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.CjDepartment), nil
	}
}

func (c cjDepartmentDo) Last() (*model.CjDepartment, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.CjDepartment), nil
	}
}

func (c cjDepartmentDo) Find() ([]*model.CjDepartment, error) {
	result, err := c.DO.Find()
	return result.([]*model.CjDepartment), err
}

func (c cjDepartmentDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CjDepartment, err error) {
	buf := make([]*model.CjDepartment, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c cjDepartmentDo) FindInBatches(result *[]*model.CjDepartment, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c cjDepartmentDo) Attrs(attrs ...field.AssignExpr) *cjDepartmentDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c cjDepartmentDo) Assign(attrs ...field.AssignExpr) *cjDepartmentDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c cjDepartmentDo) Joins(fields ...field.RelationField) *cjDepartmentDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c cjDepartmentDo) Preload(fields ...field.RelationField) *cjDepartmentDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c cjDepartmentDo) FirstOrInit() (*model.CjDepartment, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.CjDepartment), nil
	}
}

func (c cjDepartmentDo) FirstOrCreate() (*model.CjDepartment, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.CjDepartment), nil
	}
}

func (c cjDepartmentDo) FindByPage(offset int, limit int) (result []*model.CjDepartment, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c cjDepartmentDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c cjDepartmentDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c cjDepartmentDo) Delete(models ...*model.CjDepartment) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *cjDepartmentDo) withDO(do gen.Dao) *cjDepartmentDo {
	c.DO = *do.(*gen.DO)
	return c
}
